// 사용자 레포에 설치하는 AI agent 안내문 (.github/.projectops/AGENT-GUIDE.md).
//
// 왜 파일인가: 이 레포의 AGENTS.md 는 템플릿 전용이라 사용자 프로젝트로 가지 않는다. 그래서 projectops 가
// 깔린 레포에서 일하는 agent 는 "이 레포가 무엇으로 관리되는지, 옵션을 어디서 확인하는지"를 알 길이 없었다.
// 레포 루트의 AGENTS.md·CLAUDE.md 는 사용자 것이라 건드리지 않고, 폴더 안에 두고 한 줄 포인터만 안내한다.
//
// 내용에 옵션 표를 박지 않는다 — 박으면 곧 낡는다. 표는 항상 `npx projectops --mode options --json` 이 정본이다.
import { join } from "node:path";
import { writeText } from "./fsutil.js";

export const AGENT_GUIDE_PATH = ".github/.projectops/AGENT-GUIDE.md";

export function agentGuideText(templateVersion = "") {
  return `# projectops — guide for AI agents

This repository is managed with [projectops](https://github.com/Cassiiopeia/projectops)${templateVersion ? ` (installed template ${templateVersion})` : ""}.
GitHub Actions workflows in \`.github/workflows/PROJECT-*\` handle versioning, release notes, CI/CD and issue automation.
This file is generated by the installer and overwritten on update. Do not edit it.

## Ask the tool, do not guess

\`\`\`bash
npx projectops --mode options --json   # every CLI flag and every version.yml key, with allowed values and defaults
npx projectops --mode doctor           # read-only diagnosis of this install and the repository settings
\`\`\`

Both are read-only and need no network.

## Rules

- Settings live in \`version.yml\` under \`metadata.template.options\`. The options table says which keys are safe to edit by hand.
- \`version\` in \`version.yml\` is the single source of the project version. Workflows bump it on release; do not bump it by hand unless asked.
- Commit titles decide the release bump when \`semver_auto\` is on: \`feat:\` = minor, \`feat!:\` = major, anything else = patch.
- Running the installer again updates workflows. Files you changed are kept (a copy of the new version is saved in \`.github/.projectops/incoming/\`). Files you deleted are not restored.
- To stop a template workflow from ever being installed, list its file name in \`options.excluded_workflows\`.
- Run the installer from an agent or CI only with an explicit mode and \`--force\`, e.g. \`npx projectops --mode workflows --force\`. Without \`--force\` it asks questions and blocks.
- Do not edit \`.github/.projectops/logs\`, \`baseline.json\` or \`incoming/\`. They are diagnostics for the next update.
`;
}

export function installAgentGuide(targetRoot = ".", templateVersion = "") {
  writeText(join(targetRoot, AGENT_GUIDE_PATH), agentGuideText(templateVersion));
  return AGENT_GUIDE_PATH;
}
